#!/bin/sh
set -e

mkdir -p /tmp/hls

echo "[entrypoint] Aguardando panel ficar disponível..."
until wget -qO- http://panel:3000/health > /dev/null 2>&1; do
  sleep 2
done
echo "[entrypoint] Panel OK, iniciando nginx..."

envsubst '${HOOK_SECRET}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

[ -f /etc/nginx/conf.d/rtmp-push.conf ] || echo '# generated by panel' > /etc/nginx/conf.d/rtmp-push.conf

exec nginx -g 'daemon off;'
