#!/bin/sh
set -e

mkdir -p /tmp/hls

envsubst '${HOOK_SECRET}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

[ -f /etc/nginx/conf.d/rtmp-push.conf ] || echo '# generated by panel' > /etc/nginx/conf.d/rtmp-push.conf

exec nginx -g 'daemon off;'
