const router = require('express').Router();
const fs = require('fs');
const path = require('path');
const db = require('../db');
const { requireAuth, requireAdmin } = require('../auth');
const { reloadNginx } = require('../docker-reload');

const PUSH_CONF = '/app/data/nginx/rtmp-push.conf';

const PLATFORM_PRESETS = {
  youtube:   { label: 'YouTube',   url: 'rtmp://a.rtmp.youtube.com/live2/' },
  twitch:    { label: 'Twitch',    url: 'rtmp://live.twitch.tv/app/' },
  facebook:  { label: 'Facebook',  url: 'rtmps://live-api-s.facebook.com:443/rtmp/' },
  kick:      { label: 'Kick',      url: 'rtmp://fa723fc1b171.global-contribute.live-video.net/app/' },
  tiktok:    { label: 'TikTok',    url: 'rtmps://live.tiktok.com/live/' },
  instagram: { label: 'Instagram', url: 'rtmps://live-upload.instagram.com:443/rtmp/' },
  custom:    { label: 'Custom',    url: '' }
};

function generatePushConf() {
  const streams = db.prepare('SELECT * FROM streams WHERE enabled = 1').all();
  let conf = '# generated by streamrelay panel\n';
  for (const s of streams) {
    const base = s.rtmp_url.endsWith('/') ? s.rtmp_url : s.rtmp_url + '/';
    conf += `push ${base}${s.stream_key};\n`;
  }
  fs.mkdirSync(path.dirname(PUSH_CONF), { recursive: true });
  fs.writeFileSync(PUSH_CONF, conf);
}

async function applyChanges() {
  generatePushConf();
  await reloadNginx();
}

router.get('/presets', requireAuth, (req, res) => res.json(PLATFORM_PRESETS));

router.get('/', requireAuth, (req, res) => {
  res.json(db.prepare('SELECT * FROM streams ORDER BY created_at').all());
});

router.post('/', requireAuth, requireAdmin, async (req, res) => {
  const { name, platform, rtmp_url, stream_key, enabled } = req.body;
  if (!name || !platform || !rtmp_url || !stream_key) return res.status(400).json({ error: 'Missing required fields' });
  const result = db.prepare(
    'INSERT INTO streams (name, platform, rtmp_url, stream_key, enabled) VALUES (?, ?, ?, ?, ?)'
  ).run(name, platform, rtmp_url, stream_key, enabled ? 1 : 0);
  await applyChanges();
  res.status(201).json({ id: result.lastInsertRowid });
});

router.put('/:id', requireAuth, requireAdmin, async (req, res) => {
  const { name, platform, rtmp_url, stream_key, enabled } = req.body;
  db.prepare('UPDATE streams SET name=?, platform=?, rtmp_url=?, stream_key=?, enabled=? WHERE id=?')
    .run(name, platform, rtmp_url, stream_key, enabled ? 1 : 0, req.params.id);
  await applyChanges();
  res.json({ ok: true });
});

router.patch('/:id/toggle', requireAuth, requireAdmin, async (req, res) => {
  db.prepare('UPDATE streams SET enabled = 1 - enabled WHERE id = ?').run(req.params.id);
  await applyChanges();
  res.json({ ok: true });
});

router.delete('/:id', requireAuth, requireAdmin, async (req, res) => {
  db.prepare('DELETE FROM streams WHERE id = ?').run(req.params.id);
  await applyChanges();
  res.json({ ok: true });
});

module.exports = router;
